config/routes.rb
Rails.application.routes.draw do
  root 'calculadora#new'

  get  'como-funciona', to: 'home#comofunciona'
  get  'a-empresa',     to: 'home#aempresa'
  get  'search',        to: 'home#search'

  resources :contacts,    only: [:new, :create]
  resources :calculadora, only: [:new, :create]

  get  'orcamento', to: 'calculadora#orcamento'
  post 'orcamento', to: 'calculadora#orcamento'

  get  'resultado',    to: 'calculadora#resultado'
  get  'download_pdf', to: 'calculadora#download_pdf'
  post 'resultado',    to: 'calculadora#resultado'

  get 'cities_by_state', to: 'cities#cities_by_state'
  get 'state_by_city',   to: 'states#state_by_city'
  get 'fee_by_state',    to: 'states#fee_by_state'
end

app/views/layouts/shared/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="<%= carousel_item(0, slide) %>"></li>
    <li data-target="#myCarousel" data-slide-to="1" class="<%= carousel_item(1, slide) %>"></li>
    <li data-target="#myCarousel" data-slide-to="2" class="<%= carousel_item(2, slide) %>"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item bg bg1 <%= carousel_item(0, slide) %>">
      <%= render 'layouts/shared/carousel/item_carousel_01' %>
    </div>

    <div class="item bg bg2 <%= carousel_item(1, slide) %>">
      <%= render 'layouts/shared/carousel/item_carousel_02' %>
    </div>

    <div class="item bg bg3 <%= carousel_item(2, slide) %>">
      <%= render 'layouts/shared/carousel/item_carousel_03' %>
    </div>
  </div>

  <%= render partial: 'layouts/shared/links', locals: { carouselClass: 'container header-nav' } %>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="">
    <%= value %>
  </div>
<% end %>

app/views/layouts/shared/_footer.html.erb
<section class="footers pb-3 section-logo">
  <div class="container pt-1">
    <div class="row">
      <div class="col-md-1 col-sm-2">
      </div>

      <div class="col-md-2 col-sm-12">
        <div class="footers-logo">
          <%= image_tag 'logo.png', class: 'img-responsive', style: 'width:100px;' %>
        </div>

      </div>
      <div class="col-md-2 col-sm-12">
        <ul class="list-unstyled">
          <li><%= link_to 'A EMPRESA', a_empresa_path %></li>
          <li><%= link_to 'COMO FUNCIONA', como_funciona_path %></li>
          <li><%= link_to 'CALCULADORA SOLAR', new_calculadora_path %></li>
        </ul>
      </div>
      <div class="col-md-2 col-sm-12">
        <ul class="list-unstyled">
          <li><%= link_to 'ORÇAMENTO', orcamento_path %></li>
          <li><%= link_to 'CONTATO', new_contact_path %></li>

        </ul>
      </div>
      <div class="col-md-3 col-sm-12">
        <ul class="list-unstyled">
          <li><%= link_to 'CONTATO: +55 65 99914.7877', remote: true %></li>
          <li><%= image_tag '/icons/facebook.png',  style: 'width: 8%;' %><%= link_to '/NORTESULENERGIASOLAR', '#' %></li>
          <li><%= image_tag '/icons/instagram.png', style: 'width: 8%;' %><%= link_to '/NORTESULENERGIASOLAR', '#' %></li>
        </ul>
      </div>

      <div class="col-md-2 col-sm-2">
      </div>

    </div>
  </div>
</section>

<section class="footer">
  <div class="container">
    <div class="row ">
      <div class="col-md-12">
        <p>
          NORTE SUL ENERGIA SOLAR LTDA. - RUA GENERAL MASCARENHAS DE MORAIS, RONDONÓPOLIS/MT - CEP 78705-529
        </p>
        <p>TODOS OS DIREITOS RESERVADOS A NORTE E SUL ENERGIA SOLAR ®<%= Time.now.year %></p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/shared/_item_carousel.html.erb
<div class="container">

  <%= render 'layouts/shared/links' %>

  <div class="row">
    <div class="col-md-12">
      <div class="rdg-expertise-description rdg-strategy-bg-bg rdg-animated-delay-0 text-right" style="float: left;"></div>
      <div class="nav-left-text">
        <p style="margin-bottom: -2rem; color: white;">A NORTE SUL INVESTE NO</p>
        <p style="color: white;">PRESENTE E PRESERVA O FUTURO</p>
      </div>

      <div class="col-md-6">
        <%= link_to 'SIMULE AGORA', new_calculadora_path(anchor: 'calculadora'), class: 'btn btn-primary-transparent pull-left' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_links.html.erb
<div class="menu-shared <%= carouselClass %>">
  <div class="col-md-4">
    <%= link_to (image_tag 'logo-title.png', style: 'width:250px;', class: 'pull-left'), root_path %>
  </div>

  <div class="col-md-8" style="line-height: 78px;">
    <%= link_to 'A EMPRESA', a_empresa_path, class: "pull-right #{current_class?('a-empresa')}" %>
    <%= link_to 'COMO FUNCIONA', como_funciona_path, class: "pull-right #{current_class?('como-funciona')}" %>
    <%= link_to 'CALCULADORA SOLAR', new_calculadora_path(anchor: 'calculadora'), class: "pull-right #{current_class?('calculadora')}" %>
    <%= link_to 'ORÇAMENTO', orcamento_path, class: "pull-right #{current_class?('orcamento')}" %>
    <%= link_to 'CONTATO', new_contact_path, class: "pull-right #{current_class?(new_contact_path)}"%>
  </div>
</div>

app/views/layouts/shared/_navbar.html.erb
<section class="nav">
  <div class="container">
    <div class="row ">
      <div class="col-md-10 col-sm-9">
        <%= image_tag 'icon-whatsapp.png', class: 'pull-left', style: 'padding-right: 10px' %>
        <div class="topbar-text">Contato: +55 65 99914.7877</div>
      </div>

      <div class="col-md-2 col-sm-3">
        <%= link_to '#' do %>
          <%= image_tag '/icons/facebook.png', class: 'pull-left', style: 'padding-right: 10px' %>
        <% end %>

        <%= link_to '#' do %>
          <%= image_tag '/icons/instagram.png', class: 'pull-left', style: 'padding-right: 10px' %>
        <% end %>

        <%#= link_to '#' do %>
          <%#= image_tag '/icons/instagram.png', class: 'pull-left', style: 'padding-right: 10px' %>
        <%# end %>
      </div>
    </div>
  </div>
</section>