config/routes.rb
Rails.application.routes.draw do
  root 'calculadora#new'

  get  'como-funciona', to: 'home#comofunciona'
  get  'a-empresa',     to: 'home#aempresa'
  get  'search',        to: 'home#search'

  resources :contacts,    only: [:new, :create]
  resources :calculadora, only: [:new, :create]

  get  'orcamento', to: 'calculadora#orcamento'
  post 'orcamento', to: 'calculadora#orcamento'

  get  'resultado',    to: 'calculadora#resultado'
  get  'download_pdf', to: 'calculadora#download_pdf'
  post 'resultado',    to: 'calculadora#resultado'

  get 'cities_by_state', to: 'cities#cities_by_state'
  get 'state_by_city',   to: 'states#state_by_city'
  get 'fee_by_state',    to: 'states#fee_by_state'
end

app/models/calculadora.rb
class Calculadora
  include ActiveModel::Model

  attr_accessor :rede_eletrica, :estado, :cidade, :local, :ajuste, :media
  attr_accessor :nome, :telefone, :email
  attr_accessor :pdf_name

  validates_presence_of :rede_eletrica, :estado, :cidade, :local, :ajuste, :media, if: :acesso_a_rede_eletrica?
  validates_presence_of :rede_eletrica, :nome, :telefone, :email, unless: :acesso_a_rede_eletrica?

  HUMANIZED_ATTRIBUTES = {
      local:  'Tipo do local da instalação',
      ajuste: 'Ajuste da tarifa',
      media:  'Energia por mês'
  }

  MEDIA_DIAS_POR_MES   = 30
  MEDIA_HORAS_BRASIL   = 4
  MEDIA_MINIMA         = 4500
  MEDIA_MAXIMA         = 5500
  NUMERO_MESES_ANO     = 12
  NUMERO_MESES_25_ANOS = NUMERO_MESES_ANO * 25
  POTENCIA_MEDIA_PLACA = 330

  def self.human_attribute_name(attr, options = {}) # 'options' wasn't available in Rails 3, and prior versions.
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  def kwp
    kw = media.to_f / ajuste_ou_default.to_f

    (kw / MEDIA_DIAS_POR_MES) / MEDIA_HORAS_BRASIL
  end

  def ajuste_ou_default
    ajuste.nil? ? get_taxa_sem_ajuste : ajuste
  end

  def investimento_minimo
    kwp * MEDIA_MINIMA
  end

  def investimento_maximo
    kwp * MEDIA_MAXIMA
  end

  def economia_mensal
    media.to_f
  end

  def economia_anual
    economia_mensal * NUMERO_MESES_ANO
  end

  def economia_25_anos
    economia_mensal * NUMERO_MESES_25_ANOS
  end

  def retorno
    (investimento_minimo / economia_mensal) / NUMERO_MESES_ANO
  end

  def cidade_nome
    city_repository.find(cidade).name
  end

  def qtd_paineis
    (kwp / POTENCIA_MEDIA_PLACA * 100).to_i
  end

  def geracao_media
    (economia_mensal / ajuste_ou_default.to_f).to_i
  end

  private

  def acesso_a_rede_eletrica?
    rede_eletrica == 'sim'
  end

  def get_taxa_sem_ajuste
    state = state_repository.find(estado)

    case local
    when 'residencial'
      state.residencial
    when 'comercial'
      state.comercial
    when 'outro'
      state.outro
    end

  end

  def city_repository
    City
  end

  def state_repository
    State
  end
end

app/controllers/calculadora_controller.rb
class CalculadoraController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @calculadora = Calculadora.new
    @calculadora.rede_eletrica = 'sim'
  end

  def resultado
    @calculadora = Calculadora.new(calculadora_params)

    if @calculadora.valid?
      if calculadora_params[:rede_eletrica] == 'nao'
        @contact = Contact.new(calculadora_params)
        @contact.deliver
        redirect_back(fallback_location: root_path)
      end
    else
      render action: 'new'
    end
  end

  def orcamento
    if request.get?
      @calculadora = Calculadora.new

      @calculadora.local  = params[:local]         if params[:local]
      @calculadora.media  = params[:media]         if params[:media]
      @calculadora.ajuste = params[:ajuste]        if params[:ajuste]
      @calculadora.cidade = params[:cidade]        if params[:cidade]
      @calculadora.estado = params[:estado]        if params[:estado]
    else
      @contact = Contact.new(calculadora_params)
      ContactMailer.contact_message(@contact).deliver! if Rails.env.production?

      @calculadora = Calculadora.new(calculadora_params)

      # generate pdf file
      date     = Time.now.strftime('%d/%m/%Y')
      pdf_name = Time.now.to_i

      pdf_page01 = CombinePDF.load "#{Rails.root}/public/pdf/proposta_comercial_01.pdf"
      pdf_page02 = CombinePDF.load "#{Rails.root}/public/pdf/proposta_comercial_02.pdf"
      pdf_page03 = CombinePDF.load "#{Rails.root}/public/pdf/proposta_comercial_03.pdf"

      # page 01
      pdf_page01.pages[0].textbox date,              height: 20, width: 70, y: 125, x: 490, font_size: 15
      pdf_page01.pages[0].textbox @calculadora.nome, height: 10, width: 70, y: 110, x: 460, font_size: 15

      # page 02
      pdf_page02.pages[0].textbox @calculadora.qtd_paineis.to_s + '',                                                  height: 10, width: 70, y: 570, x: 460, font_size: 12
      pdf_page02.pages[0].textbox @calculadora.kwp.to_d.truncate(1).to_s + ' kWp',                                     height: 10, width: 70, y: 570, x: 340, font_size: 12
      pdf_page02.pages[0].textbox 'R$ ' + ActiveSupport::NumberHelper.number_to_delimited(@calculadora.media).to_s,    height: 10, width: 70, y: 570, x: 220, font_size: 12
      pdf_page02.pages[0].textbox @calculadora.geracao_media.to_s + " kWh/mês",                                        height: 10, width: 70, y: 570, x: 120, font_size: 12

      pdf_page02.pages[0].textbox 'R$ ' + ActiveSupport::NumberHelper.number_to_delimited(@calculadora.economia_25_anos).to_s,    height: 10, width: 70, y: 450, x: 460, font_size: 12
      pdf_page02.pages[0].textbox 'R$ ' + ActiveSupport::NumberHelper.number_to_delimited(@calculadora.economia_anual).to_s,      height: 10, width: 70, y: 450, x: 360, font_size: 12
      pdf_page02.pages[0].textbox @calculadora.retorno.to_d.truncate(1).to_s + ' ANOS',                                           height: 10, width: 70, y: 450, x: 230, font_size: 12
      pdf_page02.pages[0].textbox 'R$ ' + ActiveSupport::NumberHelper.number_to_delimited(@calculadora.investimento_minimo.round(2)).to_s, height: 10, width: 70, y: 450, x: 110, font_size: 12


      pdf = CombinePDF.new
      pdf << pdf_page01
      pdf << pdf_page02
      pdf << pdf_page03

      # pdf.save "#{Rails.root}/public/pdf/output#{pdf_name}.pdf"

      send_data pdf.to_pdf, filename: 'orcamento.pdf', type: 'application/pdf; charset=utf-8', encoding: "UTF-8"
    end
  end

  def download_pdf
    pdf = CombinePDF.load "#{Rails.root}/public/pdf/output#{params[:pdf_name]}.pdf"

    send_data pdf.to_pdf, filename: 'orcamento.pdf', type: 'application/pdf'

    #File.delete("#{Rails.root}/public/pdf/output#{params[:pdf_name]}.pdf")
  end

  private

  def calculadora_params
    params.require(:calculadora).permit(:rede_eletrica, :estado, :cidade, :local, :ajuste, :media, :nome, :email, :telefone)
  end

end

app/views/calculadora/new.html.erb
<%= render 'layouts/shared/carousel', slide: 1 %>

<section class="services">
  <div class="container">
    <div class="box carousel">

      <div id="calculadora"></div>

      <div class="row">
        <div class="col-md-12">

          <div class="row">
            <div class="nav-main-text" style="text-align: center;font-size: 60px;font-weight: 600;">
              <div>CALCULADORA SOLAR</div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= simple_form_for @calculadora, url: url_for(action: 'resultado', controller: 'calculadora', anchor: 'init'), method: 'post' do |f| %>
            <%= hidden_field_tag :local_value %>
            <%= f.hidden_field :media %>

            <div id="init"></div>

              <% if @calculadora.errors.any? %>
              <div class="alert alert-danger" role="alert">
                  <% @calculadora.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </div>
              <% end %>

              <div class="form-group">
                <p>
                  1. O local possui acesso à rede elétrica?
                </p>

                <div class="calculadora-imgs">
                  <%= f.collection_radio_buttons(:rede_eletrica, [['sim', '/icons/check'] ,['nao', '/icons/checkbox']], :first, :last, class: 'threads-opts') do |b| %>
                    <%= b.label { b.radio_button(class: 'threads-opts') + image_tag(b.text+'.png') + check_dictionary(b.text) } %>
                  <% end %>
                </div>

                <div id="rede-eletrica">

                  <p>
                    2. Onde pretende realizar a instalação?
                  </p>

                  <div class="col-md-6">
                    <%= f.input :estado, prompt: 'ESTADO', collection: State.all, label: false, input_html: { class: 'form-control'}, sytle: 'padding-right: 1px' %>
                  </div>

                  <div class="col-md-6">
                    <%= f.input :cidade, prompt: 'CIDADE', collection: City.all, label: false, input_html: { class: 'form-control'} %>
                  </div>

                  <p style="padding-top: 90px">
                    3. Qual o tipo do local da instalação?
                  </p>

                  <div class="instalacao-wrapper">
                    <%= f.collection_radio_buttons(:local, [['residencial', '/icons/residencial_azul'], ['comercial', '/icons/comercial_azul'], ['outro', '/icons/outro_azul']], :first, :last, item_wrapper_tag: "div class='col-md-3 col-md-offset-1'", class: 'threads-opts') do |b| %>
                      <%= b.label { b.radio_button(class: 'threads-opts') + image_tag(b.text+'.png', style: 'width: 70%') + local_dictionary(b.text) } %>
                    <% end %>
                  </div>

                  <div class="row">
                    <div class="col-md-6 col-md-offset-3 ajuste">
                      <%= f.input :ajuste, label: false, placeholder: 'AJUSTE DA TARIFA EM R$', input_html: { class: 'form-control center-block', style: 'text-align: center;'} %>
                    </div>
                  </div>

                  <p>
                    4. Quanto você paga de energia por mês?
                  </p>

                  <div class="valor-slider">
                    <div class="slider-wrapper">
                      <div class="slider-items dollar-sign">
                        <%= image_tag 'menor.png', style: 'height: 20px;', class: 'pull-right' %>
                      </div>
                      <div class="slider-items inside-slider">
                        <div id="slider"></div>
                      </div>
                      <div class="slider-items dollar-sign">
                        <%= image_tag 'maior.png', style: 'height: 40px' %>
                      </div>
                    </div>
                  </div>

                  <center> <%= f.button :submit, 'VER RESULTADO', class: 'btn btn-primary-outline', style: 'width: 350px; padding-top: 15px;' %> </center>
                </div>

              <div id="sem-rede-eletrica">
                <div class="form-group">
                  <p style="font-size: 20px">
                    2. Para sistemas com baterias insira seus dados para entrarmos em contato:
                  </p>

                  <div class="col-md-12">
                    <%= f.input :nome, placeholder: 'NOME', label: false, input_html: { class: 'form-control'} %>
                  </diV>

                  <div class="col-md-12">
                    <%= f.input :email, placeholder: 'E-MAIL', label: false, input_html: { class: 'form-control'} %>
                  </diV>

                  <div class="col-md-12">
                    <%= f.input :telefone, placeholder: 'TELEFONE', label: false, input_html: { class: 'form-control'} %>
                  </div>
                </div>

                <center> <%= f.button :submit, 'ENVIAR', :class=> "btn btn-primary", style: 'width: 350px; margin-top: 40px' %> </center>

              </div>

            </div>

         <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
    $(document).ready(function(){
        const startAmount = 7500;

        initPreferences = function () {
            //Added, set initial value.
            $("#amount").val(startAmount);
            $("#duration").val(startAmount);
            $("#amount-label").text(startAmount);
            $("#duration-label").text(startAmount);

            update();

            $('#calculadora_rede_eletrica_sim').next('img').attr("src", "/icons/check.png");
            $('#calculadora_rede_eletrica_nao').next('img').attr("src", "/icons/checkbox.png");

            $("#calculadora_ajuste").inputmask('decimal', {
              'alias': 'numeric',
              // 'groupSeparator': ',',
              // 'digits': 2,
              // 'prefix': 'R$ ',
            });

            if($("input[name='calculadora[rede_eletrica]']:checked").val() == 'sim') {
                $("#rede-eletrica").show();
                $("#sem-rede-eletrica").hide();
                $('#calculadora_rede_eletrica_sim').prop('checked', true).trigger("click");
            } else {
                $("#rede-eletrica").hide();
                $("#sem-rede-eletrica").show();
                $('#calculadora_rede_eletrica_nao').prop('checked', true).trigger("click");
            }

            $('#calculadora_ajuste').css('text-align','center');
        }();


        $("#calculadora_estado").change(function() {
            getCitiesByState("id="+$("#calculadora_estado").val());

            getFeeByState();
        });

        $("#calculadora_cidade").change(function() {
            getStateByCity("id="+$("#calculadora_cidade").val());
        });

        function getFeeByState() {
            let local = $("#local_value").val();

            if(local != undefined && $("#calculadora_estado").val() != undefined){
                $.ajax({
                    type: 'GET',
                    data:{
                        state_id: $("#calculadora_estado").val(),
                        local:    $("input[name='calculadora[local]']").val(),
                    },
                    url: '/fee_by_state/',

                    success: function(data){

                        switch(local) {
                            case 'residencial':
                                $("#calculadora_ajuste").val(data['state']['residencial']);
                                break;
                            case 'comercial':
                                $("#calculadora_ajuste").val(data['state']['comercial']);
                                break;
                            case 'outro':
                                $("#calculadora_ajuste").val(data['state']['outro']);
                                break;
                        }
                    }
                });
            }
        }

        function getCitiesByState(id) {
            $.getJSON("/cities_by_state", id, function (j) {
                var options = '<option value="">CIDADE</option>';
                $.each(j.cty, function (i, item) {
                    options += '<option value="' + item.id + '">' + item.n + '</option>';
                });
                $("#calculadora_cidade").html(options);
            });
        }

        function getStateByCity(id) {
            $.getJSON("/state_by_city", id, function (j) {
                $("#calculadora_estado").val(j['state']['id']);
            });
        }

        $("input[name='calculadora[rede_eletrica]']").click(function(){
            switch($(this).val()) {
                case 'sim':
                    $('#calculadora_rede_eletrica_sim').next('img').attr("src", "/icons/check.png");
                    $('#calculadora_rede_eletrica_nao').next('img').attr("src", "/icons/checkbox.png");

                    $("#rede-eletrica").show();
                    $("#sem-rede-eletrica").hide();

                    break;
                case 'nao':
                    $('#calculadora_rede_eletrica_sim').next('img').attr("src", "/icons/checkbox.png");
                    $('#calculadora_rede_eletrica_nao').next('img').attr("src", "/icons/check.png");

                    $("#rede-eletrica").hide();
                    $("#sem-rede-eletrica").show();

                    break;
            }
        });

        $("input[name='calculadora[local]']").click(function(){
            $("#local_value").val($(this).val());

            getFeeByState();

            switch($(this).val()) {
                case 'residencial':
                    $('#calculadora_local_residencial').next('img').attr("src", "/icons/residencial_amarelo.png");
                    $('#calculadora_local_comercial').next('img').attr("src", "/icons/comercial_azul.png");
                    $('#calculadora_local_outro').next('img').attr("src", "/icons/outro_azul.png");

                    break;
                case 'comercial':
                    $('#calculadora_local_residencial').next('img').attr("src", "/icons/residencial_azul.png");
                    $('#calculadora_local_comercial').next('img').attr("src", "/icons/comercial_amarelo.png");
                    $('#calculadora_local_outro').next('img').attr("src", "/icons/outro_azul.png");

                    break;

                case 'outro':
                    $('#calculadora_local_residencial').next('img').attr("src", "/icons/residencial_azul.png");
                    $('#calculadora_local_comercial').next('img').attr("src", "/icons/comercial_azul.png");
                    $('#calculadora_local_outro').next('img').attr("src", "/icons/outro_amarelo.png");

                    break;
            }
        });
        $("#slider").slider({
            animate: true,
            value:startAmount,
            min: 100,
            max: 15000,
            step: 10,
            slide: function(event, ui) {
                update(1,ui.value);
            }
        });
        $('#slider a').html('<label><span class="glyphicon glyphicon-chevron-left"></span> '+ startAmount +' <span class="glyphicon glyphicon-chevron-right"></span></label>');

        //changed. now with parameter
        function update(slider,val) {

            //changed. Now, directly take value from ui.value. if not set (initial, will use current value.)
            var $amount = slider == 1?val:$("#amount").val();
            var $duration = slider == 2?val:$("#duration").val();

            if ($amount == undefined) {
                $amount = startAmount;
                $duration = 1;
            }

            /* commented
            $amount = $( "#slider" ).slider( "value" );
             */

            $total = "$" + ($amount * $duration);
            $( "#amount" ).val($amount);
            $( "#amount-label" ).text($amount);
            $( "#duration" ).val($duration);
            $( "#duration-label" ).text($duration);
            $( "#total" ).val($total);
            $( "#total-label" ).text($total);

            $('#slider a').html('<label><span class="glyphicon glyphicon-chevron-left"></span> '+$amount+' <span class="glyphicon glyphicon-chevron-right"></span></label>');

            $('#calculadora_media').val($amount);
        }

    });
</script>

app/views/calculadora/resultado.html.erb
<%= render 'layouts/shared/carousel', slide: 2 %>

<%= hidden_field_tag :pdf_name, @pdf_name %>

<section class="services">
  <div class="container">
    <div class="box carousel">

      <div class="row">
        <div class="col-md-12">

          <%= link_to 'Download', download_pdf_path(pdf_name: @pdf_name), id: 'download_pdf', class: 'download_pdf' %>

          <div id="init"></div>

          <div class="row">
            <div class="nav-main-text" style="text-align: center;font-size: 60px;font-weight: 600;">
              <div id="calculadora">CALCULADORA SOLAR</div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <figure class="card card-product">
            <figcaption class="info-wrap">
              <h4 class="title card-title"><%= image_tag '/icons/resultado_investimento.png', style: 'height: 50px; border: 0; padding: 0' %>INVESTIMENTO</h4>
            </figcaption>
            <div class="bottom-wrap">
              <p>De <%= number_to_currency(@calculadora.investimento_minimo) %> a <%= number_to_currency(@calculadora.investimento_maximo) %></p>
              <hr style="height:2px;border:none;color:gray;background-color:gray;padding-left: 50px;width: 50px;">
              <p>Economia mensal:</p>
              <p><%= number_to_currency(@calculadora.media) %></p>
              <p>Economia anual:</p>
              <p><%= number_to_currency(@calculadora.economia_anual) %></p>
              <p>Economia total em 25 anos:</p>
              <p><%= number_to_currency(@calculadora.economia_25_anos) %></p>
            </div>
          </figure>
        </div>

        <div class="col-md-4">
          <figure class="card card-product">
            <figcaption class="info-wrap">
              <h4 class="title card-title"><%= image_tag '/icons/resultado_ambiente.png', style: 'height: 50px; border: 0; padding: 0' %>AMBIENTE</h4>
            </figcaption>
            <div class="bottom-wrap">
              <p>Equivalente a 10.000 KM de </p>
              <p>carro elétrico</p>
              <hr style="height:2px;border:none;color:gray;background-color:gray;padding-left: 50px;width: 50px;">
              <p>Redução de CO2 na atmosfera</p>
              <p>Equivalente a centenas  de árvores plantadas</p>
              <p>Equivalente a milhares  de KM rodados de um  carro</p>
            </div>
          </figure>
        </div>

        <div class="col-md-4">
          <figure class="card card-product">
            <figcaption class="info-wrap">
              <h4 class="title card-title"><%= image_tag '/icons/resultado_sistema.png', style: 'height: 50px; border: 0; padding: 0' %>SISTEMA INDICADO</h4>
            </figcaption>
            <div class="bottom-wrap">
              <p><%= number_with_delimiter(@calculadora.kwp.round(2)) %> kWp</p>
              <hr style="height:2px;border:none;color:gray;background-color:gray;padding-left: 50px;width: 50px;">
              <p>Tamanho da Potência:</p>
              <p><%= number_with_delimiter(@calculadora.kwp.round(2)) %> kWp</p>
              <p>Número de Módulos:</p>
              <p><%= @calculadora.qtd_paineis %> módulos</p>
              <p>Produção Estimada:</p>
              <p><%= @calculadora.geracao_media %> kw/h</p>
            </div>
          </figure>
        </div>
      </div>

      <div class="col-md-6">
        <%= link_to 'REINCIAR CALCULADORA', new_calculadora_path(anchor: 'calculadora'), class: 'btn btn-primary btn-block pull-right' %>
      </div>

      <div class="col-md-6">
        <%= link_to 'SOLICITE ORÇAMENTO', orcamento_path(
                                                        media:   params[:calculadora][:media],
                                                        estado:  params[:calculadora][:estado],
                                                        cidade:  params[:calculadora][:cidade],
                                                        local:   params[:calculadora][:local],
                                                        ajuste:  params[:calculadora][:ajuste],
                                                        ), class: 'btn btn-primary-outline btn-block pull-left' %>
      </div>

      <br><br><br>

    </div>
  </div>
</section>

<script>
    $(document).ready(function(){
        init = function () {
            //$('#download_pdf')[0].click();
            //$(window).scrollTop($('#download_pdf').offset().top);
        }();
    });
</script>